
name: CI - protoc-gen-nanopb

on:
  push:
    tags:
      - 'protoc-gen-nanopb/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/tags/protoc-gen-nanopb/})"
        id: tag
        
      - name: Login to Buf build
        uses: docker/login-action@v2
        with:
          registry: plugins.buf.build
          username: ${{ secrets.BUF_BUILD_API_USER }}
          password: ${{ secrets.BUF_BUILD_API_KEY }}
     
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: protoc-gen-nanopb
          push: true
          tags: plugins.buf.build/euskadi31/protoc-gen-nanopb:${{ steps.tag.outputs.name }}-1
