name: Docker Release

on:
  workflow_call:
    secrets:
      BUF_BUILD_API_USER:
        required: true
      BUF_BUILD_API_KEY:
        required: true
    inputs:
      plugin_name:
        required: true
        type: string
    
defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/tags/${{ inputs.plugin_name }}/})"
        id: tag
        
      - name: Login to Buf build
        uses: docker/login-action@v2
        with:
          registry: plugins.buf.build
          username: ${{ secrets.BUF_BUILD_API_USER }}
          password: ${{ secrets.BUF_BUILD_API_KEY }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.plugin_name }}
          push: true
          tags: plugins.buf.build/euskadi31/${{ inputs.plugin_name }}:${{ steps.tag.outputs.name }}-1










  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if a new release
        uses: actions/github-script@v6
        id: version
        with:
          script: |
            const tags = await github.rest.repos.listTags({
              owner: '${{ inputs.owner_name }}',
              repo: '${{ inputs.repo_name }}'
            });

            const version = tags.data[0].name.replace('nanopb-', '').replace('v', '');

            console.log(version);

            return version;
          result-encoding: string

      - name: Check if already released
        uses: actions/github-script@v6
        id: check
        with:
          script: |
            const tags = await github.rest.repos.listTags({
              owner: 'euskadi31',
              repo: 'buf-plugins',
              per_page: 100
            });

            const found = tags.data.find(tag => tag.name === '${{ inputs.plugin_name }}/v${{ steps.version.outputs.result }}');

            // tags already exists => stop
            if (found) {
              return false;
            }

            return true;

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        if: ${{steps.check.outputs.result == 'true'}}
        with:
          go-version: '1.18.3'
        id: go

      - name: Checkout
        if: ${{steps.check.outputs.result == 'true'}}
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Generate Dockerfile
        if: ${{steps.check.outputs.result == 'true'}}
        run: go run builder/main.go ${{steps.version.outputs.result}} ${{ inputs.plugin_name }}/Dockerfile.tpl ${{ inputs.plugin_name }}/Dockerfile

      - name: Commit new Dockerfile
        if: ${{steps.check.outputs.result == 'true'}}
        run: |
          cat ${{ inputs.plugin_name }}/Dockerfile
          git config --global user.name 'euskadi31'
          git config --global user.email 'euskadi31@users.noreply.github.com'
          git add .
          git commit -am "Bumb ${{ inputs.plugin_name }} v${{steps.version.outputs.result}}" || true
          git tag -a ${{ inputs.plugin_name }}/v${{steps.version.outputs.result}} -m "Release ${{ inputs.plugin_name }} v${{steps.version.outputs.result}}"
          git push
          git push --tags

