name: Docker Release

on:
  workflow_call:
    secrets:
      BUF_BUILD_API_USER:
        required: true
      BUF_BUILD_API_KEY:
        required: true
    inputs:
      plugin_name:
        required: true
        type: string
    
defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/tags/${{ inputs.plugin_name }}/})"
        id: tag
        
      - name: Login to Buf build
        uses: docker/login-action@v2
        with:
          registry: plugins.buf.build
          username: ${{ secrets.BUF_BUILD_API_USER }}
          password: ${{ secrets.BUF_BUILD_API_KEY }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.plugin_name }}
          push: true
          tags: plugins.buf.build/euskadi31/${{ inputs.plugin_name }}:${{ steps.tag.outputs.name }}-1
